import test from 'node:test';
import assert from 'node:assert/strict';
import {listDetectedTeachers,parseIndexEducationPages,resolveTeacherPage} from '../pdf-layout-parser.js';

function item(str,x,y,width=40,height=10){return{str,x,y,width,height}}
function page(number,name,lessonText=''){const items=[item(name,220,35,120),...['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'].map((d,i)=>item(d,100+i*80,60,60)),item('08:00 – 09:00',20,145,70),item('09:00 – 10:00',20,205,70),item('10:00 – 11:00',20,265,70)];if(lessonText)items.push(item(lessonText,105,130,55),item('ROSSI M.',105,140,45),item('3° A',105,150,30),item('Aula 12',105,160,45));return{number,width:600,height:400,items}}

test('seleziona soltanto la pagina intestata al docente',()=>{const result=parseIndexEducationPages([page(1,'BIANCHI ANNA','Italiano'),page(2,'THOMAS DE ANGELIS','Pasticceria')],{firstName:'Thomas',lastName:'De Angelis',fullName:'Thomas De Angelis'},{maxPeriods:10});assert.equal(result.pageNumber,2);assert.equal(result.lessons[0].className,'3°A');assert.equal(result.lessons[0].room,'12');assert.match(result.lessons[0].subject,/Pasticceria/);assert.deepEqual(result.lessons[0].coTeachers,['ROSSI M.'])});

test('mantiene fasce pomeridiane e periodi oltre la sesta ora',()=>{const p=page(1,'THOMAS DE ANGELIS');p.items=p.items.filter(i=>!/^0[89]:|^10:/.test(i.str));for(let i=0;i<8;i++){const h=8+i;p.items.push(item(`${String(h).padStart(2,'0')}:00 – ${String(h+1).padStart(2,'0')}:00`,20,130+i*30,75))}p.items.push(item('5° B',185,340,30),item('Laboratorio',185,348,65));const result=parseIndexEducationPages([p],{fullName:'Thomas De Angelis',firstName:'Thomas',lastName:'De Angelis'},{maxPeriods:10});const lesson=result.lessons.find(l=>l.day===1);assert.equal(lesson.period,7);assert.equal(lesson.time,'15:00 – 16:00')});

test('non dipende dall ordine testuale degli elementi PDF',()=>{const p=page(1,'THOMAS DE ANGELIS','Pasticceria');p.items.reverse();const result=parseIndexEducationPages([p],{fullName:'Thomas De Angelis',firstName:'Thomas',lastName:'De Angelis'});assert.equal(result.lessons[0].day,0);assert.equal(result.lessons[0].period,0)});

test('espande una lezione graficamente alta su piu ore',()=>{const p=page(1,'THOMAS DE ANGELIS','Pasticceria');p.boxes=[{left:90,right:170,top:112,bottom:230}];const result=parseIndexEducationPages([p],{fullName:'Thomas De Angelis',firstName:'Thomas',lastName:'De Angelis'});assert.deepEqual(result.lessons.map(l=>l.period),[0,1])});

test('riconosce cognome nome e una forma abbreviata non ambigua del nome',()=>{const match=resolveTeacherPage([page(146,'RAIOLA ANGELO'),page(147,'ROSSI MICHELE')],{firstName:'Michelangelo',lastName:'Raiola',fullName:'Michelangelo Raiola'});assert.equal(match.status,'matched');assert.equal(match.pageNumber,146);assert.equal(match.name,'RAIOLA ANGELO')});

test('riconosce iniziali ma non sceglie quando la corrispondenza e ambigua',()=>{const pages=[page(1,'ROSSI MARIO'),page(2,'ROSSI MARCO')];const match=resolveTeacherPage(pages,{firstName:'M.',lastName:'Rossi',fullName:'M. Rossi'});assert.equal(match.status,'ambiguous');assert.equal(match.candidates.length,2)});

test('estrae solo le intestazioni dei docenti, non le compresenze nella griglia',()=>{const p=page(146,'RAIOLA ANGELO','SCIENZE ALIMENTARI');assert.deepEqual(listDetectedTeachers([p]).map(t=>t.name),['RAIOLA ANGELO'])});

test('permette di analizzare una pagina scelta manualmente',()=>{const pages=[page(1,'ROSSI MARIO','Italiano'),page(2,'BIANCHI ANNA','Matematica')];const result=parseIndexEducationPages(pages,{firstName:'Nome',lastName:'Assente',fullName:'Nome Assente'},{pageNumber:2});assert.equal(result.pageNumber,2);assert.match(result.lessons[0].subject,/Matematica/)});

test('ignora ora di stampa, intestazioni dei giorni e testo fuori griglia',()=>{const p=page(146,'RAIOLA ANGELO','SCIENZE ALIMENTARI');p.items.push(item('11/09/2026 08:31 - Pagina 146',430,30,140),item('lunedì 14/09',75,60,65),item('Orario in vigore dal 14 settembre 2026',380,385,180));const result=parseIndexEducationPages([p],{firstName:'Michelangelo',lastName:'Raiola',fullName:'Michelangelo Raiola'});assert.ok(result.lessons.length>0);assert.ok(result.lessons.every(l=>!l.subject.match(/LUNED|MARTED|MERCOLED|GIOVED|VENERD|SABAT/i)));assert.ok(result.lessons.every(l=>l.time!=='08:31 – 08:00'))});

test('usa sempre il fallback testuale se i rettangoli grafici non sono riconoscibili',()=>{const p=page(146,'RAIOLA ANGELO','SCIENZE ALIMENTARI');p.boxes=[{left:5,top:5,right:20,bottom:20}];const result=parseIndexEducationPages([p],{firstName:'Michelangelo',lastName:'Raiola',fullName:'Michelangelo Raiola'});assert.ok(result.lessons.length>0);assert.match(result.lessons[0].subject,/SCIENZE ALIMENTARI/)});

test('ricostruisce visivamente i blocchi reali della pagina 146',()=>{const items=[item('RAIOLA ANGELO',247,45,100),...['lunedì 14/09','martedì 15/09','mercoledì 16/09','giovedì 17/09','venerdì 18/09','sabato 19/09'].map((d,i)=>item(d,70+i*80,60,60)),item('11/09/2026 08:31 - Pagina 146',455,30,110)];for(let h=8;h<=18;h++)items.push(item(`${h}h00`,35,70+(h-8)*48,22));items.push(item('SCIENZE ALIMENTARI',150,172,72),item('GIANOTTI S.',165,184,45),item('4ARD',176,195,25),item('B2.3',177,205,22),item('LAB. SERVIZI ENOGASTRONOMICI',145,300,78),item('5APS',178,308,24),item('A2.8',179,316,22),item('LAB. SERV.CUCINA',235,244,68),item('4ARD',258,256,24),item('FORNI CUCINA',240,268,60),item('LAB. SERV.CUCINA',315,244,68),item('4ARD',338,256,24),item('FORNI CUCINA',320,268,60),item('DISPOSIZIONE',405,212,58),item('SCIENZE ALIMENTARI',485,220,72),item('BALLISTA I.',505,232,44),item('3ARP',515,244,23),item('A3.4',516,255,22));const boxes=[{left:140,right:220,top:166,bottom:214},{left:140,right:220,top:262,bottom:358},{left:220,right:300,top:166,bottom:358},{left:300,right:380,top:166,bottom:358},{left:380,right:460,top:166,bottom:262},{left:460,right:540,top:214,bottom:262}];const result=parseIndexEducationPages([{number:146,width:595,height:842,items,boxes}],{firstName:'Michelangelo',lastName:'Raiola',fullName:'Michelangelo Raiola'},{maxPeriods:10});const at=(day,period)=>result.lessons.find(l=>l.day===day&&l.period===period),count=day=>result.lessons.filter(l=>l.day===day).length;assert.deepEqual(result.periodTimes,['08:00 – 09:00','09:00 – 10:00','10:00 – 11:00','11:00 – 12:00','12:00 – 13:00','13:00 – 14:00']);assert.equal(result.detectedMaxPeriods,6);assert.equal(count(0),0);assert.equal(at(1,2).time,'10:00 – 11:00');assert.equal(at(1,2).className,'4°ARD');assert.equal(at(1,2).subject,'SCIENZE ALIMENTARI');assert.equal(at(1,2).room,'B2.3');assert.deepEqual(at(1,2).coTeachers,['GIANOTTI S.']);assert.equal(at(1,3),undefined);assert.equal(at(1,4).subject,'LAB. SERVIZI ENOGASTRONOMICI');assert.equal(at(1,5).subject,'LAB. SERVIZI ENOGASTRONOMICI');assert.equal(count(2),4);assert.equal(at(2,2).room,'FORNI CUCINA');assert.equal(count(3),4);assert.equal(at(4,2).subject,'DISPOSIZIONE');assert.equal(at(4,3).subject,'DISPOSIZIONE');assert.equal(count(4),2);assert.equal(at(5,3).room,'A3.4');assert.ok(!result.lessons.some(l=>l.time.includes('08:31')))});
